---
name: Class-Meta-Express
version: 0.10
author:
  - 'David Wheeler <david@kineticode.com>'
abstract: 'Concise, expressive creation of Class::Meta classes'
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  Class::Meta: 0.60
build_requires:
  Test::More: 0.17
recommends:
  Test::Pod: 1.20
provides:
  Class::Meta::Express:
    file: lib/Class/Meta/Express.pm
    version: 0.10
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
